kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: dev-hello
  namespace: dev-environment
  labels:
    app.kubernetes.io/name: taxi
    app.kubernetes.io/version: 0.0.1
spec:
  to:
    kind: Service
    name: taxi
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
